//1
const age=19;
const height="59";
if(age>18 && height>60){
    console.log("Gari Theloo");
}
else{
    console.log("choto garite boso");
}
//2
const mathNumber=99;
const englishNumber=67;
if(mathNumber>80 || englishNumber>85)
{
    console.log("Eligible for admission");

}
else{
    console.log("Sorry!!Not eligible");
}
//3
const studentGPA=5.00;
const familyMonthlyincome=10500;
if(studentGPA==5.00 && familyMonthlyincome<=10000)
{
    console.log("Eligible for Schlarship");

}
else
{
    console.log("Not eligible for Schlarship");

}
//4
const jobAge=25;
const experience=1.5;
if(jobAge<30 && experience>2)
    console.log("You can apply for this job.")
else
{
    console.log("Sorry, you cannot apply for this job");
}
//5
const numberOfEgg=11;
const haveChicken=true;
if(numberOfEgg>12 || haveChicken==false)
{
    console.log("Eat Dim er Korma");

}
else{
    console.log("eat Ruti & Kola");
}
//6
const bodyTemp=102;
const haveCough=false;
if(bodyTemp>100 || haveCough==true)
{
    console.log("Go to doctor");
}else{
    console.log("Take rest");
}
//7
const attendenceParcentage=84;
const assignHomework=false;
if(attendenceParcentage>80 && assignHomework==true)
{
    console.log("You can apply for Final Exam");
}
else{
    console.log("Auto Fail");
}
//8
const powerSupply="on";
const haveChargeInPhone=false;
if(powerSupply=="off" && haveChargeInPhone==false)
{
    console.log("porte bosh!!");

}
else{
    console.log("Game Khel");
}
//9
const shirtPrice=1250;
if(shirtPrice>1000)
    console.log("20% Discount");
else{
    console.log("No Discount");
}